name: Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: ${{ matrix.platform }} — Xcode ${{ matrix.xcode }} (${{ matrix.macos }})
    runs-on: ${{ matrix.macos }}
    strategy:
      matrix:
        xcode: ['14.2', '14.0.1', '13.4.1', '13.1']
        macos: ['macos-12', 'macos-11']
        platform: ['macOS', 'iOS', 'tvOS', 'watchOS', 'mac-catalyst']
    steps:
    - uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: ${{ matrix.xcode }}
    - uses: mxcl/xcodebuild@v1.9.2
      with:
        workspace: 'Examples/WatchDatePickerExamples.xcodeproj'
        platform: ${{ matrix.platform }}
        scheme: WatchDatePicker
        action: build analyze
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
